kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: webapplication3
spec:
  replicas: 1
  template:
    metadata:
      name: 
      labels:
        app: webapplication3
    spec:
      containers:
      - name: webapplication3
        image: rkulkarnidevopsdemo.azurecr.io/webapplication2:v1
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 20
          timeoutSeconds: 5
        ports:
        - name: web
          containerPort: 80       
      imagePullSecrets:
        - name: myregistrykey

        