kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: bluegreendeploymentdemov1
spec:
  replicas: 1
  template:
    metadata:
      name: 
      labels:
        app: bluegreendeploymentdemov1
    spec:
      containers:
      - name: bluegreendeploymentdemov1
        image: rkulkarnidevopsdemo.azurecr.io/bluegreendeploymentdemo:v2
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 20
          timeoutSeconds: 5
        ports:
        - name: web
          containerPort: 8080       
      imagePullSecrets:
        - name: myregistrykey

        
