version: '2.1'

services:
  bluegreendeploymentdemo:
    image: bluegreendeploymentdemo:dev
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    volumes:
      - .\BlueGreenDeploymentDemo:C:\inetpub\wwwroot
      - ~\msvsmon:C:\msvsmon:ro
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=windows"
