kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: [DeploymentName]
spec:
  replicas: 1
  template:
    metadata:
      name: 
      labels:
        app: [DeploymentName]
    spec:
      containers:
      - name: [DeploymentName]
        image: rkulkarnidevopsdemo.azurecr.io/bluegreendeploymentdemo:v[VersionNumber]
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 20
          timeoutSeconds: 5
        ports:
        - name: web
          containerPort: 80       
      imagePullSecrets:
        - name: myregistrykey
