kind: Pod
apiVersion: v1
metadata:
  name: blue
    spec:
      containers:
      - name: blue
        image: rkulkarnidevopsdemo.azurecr.io/bluegreendeploymentdemo:v4
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 20
          timeoutSeconds: 5
        ports:
        - name: web
          containerPort: 80       
      imagePullSecrets:
        - name: myregistrykey

        
