kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: bluegreendeploymentdemov2
spec:
  replicas: 1
  template:
    metadata:
      name: 
      labels:
        app: bluegreendeploymentdemov2
    spec:
      containers:
      - name: bluegreendeploymentdemov2
        image: rkulkarnidevopsdemo.azurecr.io/bluegreendeploymentdemo:v3
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 20
          timeoutSeconds: 5
        ports:
        - name: web
          containerPort: 80       
      imagePullSecrets:
        - name: myregistrykey

        
