kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: green
spec:
  replicas: 1
  template:
    metadata:
      name: 
      labels:
        app: green
    spec:
      containers:
      - name: green
        image: rkulkarnidevopsdemo.azurecr.io/bluegreendeploymentdemo:v8
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 20
          timeoutSeconds: 5
        ports:
        - name: web
          containerPort: 80       
      imagePullSecrets:
        - name: myregistrykey
